[[bin]]
name = "leetcode"
path = "src/bin/lc.rs"

[package]
name = "leetcode-cli"
version = "0.4.6"
authors = ["clearloop <tianyi.gc@gmail.com>"]
edition = "2021"
description = "Leetcode command-line interface in rust."
repository = "https://github.com/clearloop/leetcode-cli"
license = "MIT"
documentation = "https://docs.rs/leetcode_cli"
homepage = "https://github.com/clearloop/leetcode-cli"
keywords = ["cli", "games", "leetcode"]
readme = './README.md'

[dependencies]
async-trait = "0.1.86"
tokio = { version = "1.43.0", features = ["full"] }
clap = { version = "4.5.31", features = ["cargo"] }
colored = "3.0.0"
dirs = "6.0.0"
env_logger = "0.11.6"
keyring = "3.6.2"
log = "0.4.26"
openssl = "0.10.71"
pyo3 = { version = "0.23.5", optional = true }
rand = "0.9.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
toml = "0.8.20"
regex = "1.11.1"
scraper = "0.23.1"
anyhow = "1.0.96"
clap_complete = "4.5.46"
thiserror = "2.0.11"

[dependencies.diesel]
version = "2.2.7"
features = ["sqlite"]

[dependencies.reqwest]
version = "0.12.12"
features = ["gzip", "json"]

[features]
pym = ["pyo3"]

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.29.0", features = [ "signal" ] }
